/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UneteRouteImport } from './routes/unete'
import { Route as SedesRouteImport } from './routes/sedes'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as PedidoConfirmadoRouteImport } from './routes/pedido-confirmado'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as ModeradorRouteImport } from './routes/moderador'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as CajeroRouteImport } from './routes/cajero'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModeradorIndexRouteImport } from './routes/moderador.index'
import { Route as CajeroIndexRouteImport } from './routes/cajero.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'
import { Route as ModeradorHistorialRouteImport } from './routes/moderador.historial'
import { Route as CajeroHistorialRouteImport } from './routes/cajero.historial'
import { Route as ApiStaffUsersRouteImport } from './routes/api.staff-users'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminSedesRouteImport } from './routes/admin.sedes'
import { Route as AdminReportesRouteImport } from './routes/admin.reportes'
import { Route as AdminProductosRouteImport } from './routes/admin.productos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminOperacionRouteImport } from './routes/admin.operacion'
import { Route as AdminMarcasRouteImport } from './routes/admin.marcas'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'

const UneteRoute = UneteRouteImport.update({
  id: '/unete',
  path: '/unete',
  getParentRoute: () => rootRouteImport,
} as any)
const SedesRoute = SedesRouteImport.update({
  id: '/sedes',
  path: '/sedes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoConfirmadoRoute = PedidoConfirmadoRouteImport.update({
  id: '/pedido-confirmado',
  path: '/pedido-confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeradorRoute = ModeradorRouteImport.update({
  id: '/moderador',
  path: '/moderador',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const CajeroRoute = CajeroRouteImport.update({
  id: '/cajero',
  path: '/cajero',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeradorIndexRoute = ModeradorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModeradorRoute,
} as any)
const CajeroIndexRoute = CajeroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CajeroRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeradorHistorialRoute = ModeradorHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => ModeradorRoute,
} as any)
const CajeroHistorialRoute = CajeroHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => CajeroRoute,
} as any)
const ApiStaffUsersRoute = ApiStaffUsersRouteImport.update({
  id: '/api/staff-users',
  path: '/api/staff-users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSedesRoute = AdminSedesRouteImport.update({
  id: '/sedes',
  path: '/sedes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperacionRoute = AdminOperacionRouteImport.update({
  id: '/operacion',
  path: '/operacion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarcasRoute = AdminMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cajero': typeof CajeroRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/moderador': typeof ModeradorRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/productos': typeof ProductosRoute
  '/sedes': typeof SedesRoute
  '/unete': typeof UneteRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/operacion': typeof AdminOperacionRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/sedes': typeof AdminSedesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/staff-users': typeof ApiStaffUsersRoute
  '/cajero/historial': typeof CajeroHistorialRoute
  '/moderador/historial': typeof ModeradorHistorialRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/cajero/': typeof CajeroIndexRoute
  '/moderador/': typeof ModeradorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/productos': typeof ProductosRoute
  '/sedes': typeof SedesRoute
  '/unete': typeof UneteRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/operacion': typeof AdminOperacionRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/sedes': typeof AdminSedesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/staff-users': typeof ApiStaffUsersRoute
  '/cajero/historial': typeof CajeroHistorialRoute
  '/moderador/historial': typeof ModeradorHistorialRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/cajero': typeof CajeroIndexRoute
  '/moderador': typeof ModeradorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cajero': typeof CajeroRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/moderador': typeof ModeradorRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/productos': typeof ProductosRoute
  '/sedes': typeof SedesRoute
  '/unete': typeof UneteRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/operacion': typeof AdminOperacionRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/sedes': typeof AdminSedesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/staff-users': typeof ApiStaffUsersRoute
  '/cajero/historial': typeof CajeroHistorialRoute
  '/moderador/historial': typeof ModeradorHistorialRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/cajero/': typeof CajeroIndexRoute
  '/moderador/': typeof ModeradorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cajero'
    | '/carrito'
    | '/catalogo'
    | '/checkout'
    | '/contacto'
    | '/login'
    | '/moderador'
    | '/nosotros'
    | '/pedido-confirmado'
    | '/productos'
    | '/sedes'
    | '/unete'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/configuracion'
    | '/admin/marcas'
    | '/admin/operacion'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/sedes'
    | '/admin/usuarios'
    | '/api/staff-users'
    | '/cajero/historial'
    | '/moderador/historial'
    | '/producto/$slug'
    | '/admin/'
    | '/cajero/'
    | '/moderador/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrito'
    | '/catalogo'
    | '/checkout'
    | '/contacto'
    | '/login'
    | '/nosotros'
    | '/pedido-confirmado'
    | '/productos'
    | '/sedes'
    | '/unete'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/configuracion'
    | '/admin/marcas'
    | '/admin/operacion'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/sedes'
    | '/admin/usuarios'
    | '/api/staff-users'
    | '/cajero/historial'
    | '/moderador/historial'
    | '/producto/$slug'
    | '/admin'
    | '/cajero'
    | '/moderador'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cajero'
    | '/carrito'
    | '/catalogo'
    | '/checkout'
    | '/contacto'
    | '/login'
    | '/moderador'
    | '/nosotros'
    | '/pedido-confirmado'
    | '/productos'
    | '/sedes'
    | '/unete'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/configuracion'
    | '/admin/marcas'
    | '/admin/operacion'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/sedes'
    | '/admin/usuarios'
    | '/api/staff-users'
    | '/cajero/historial'
    | '/moderador/historial'
    | '/producto/$slug'
    | '/admin/'
    | '/cajero/'
    | '/moderador/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CajeroRoute: typeof CajeroRouteWithChildren
  CarritoRoute: typeof CarritoRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactoRoute: typeof ContactoRoute
  LoginRoute: typeof LoginRoute
  ModeradorRoute: typeof ModeradorRouteWithChildren
  NosotrosRoute: typeof NosotrosRoute
  PedidoConfirmadoRoute: typeof PedidoConfirmadoRoute
  ProductosRoute: typeof ProductosRoute
  SedesRoute: typeof SedesRoute
  UneteRoute: typeof UneteRoute
  ApiStaffUsersRoute: typeof ApiStaffUsersRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unete': {
      id: '/unete'
      path: '/unete'
      fullPath: '/unete'
      preLoaderRoute: typeof UneteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sedes': {
      id: '/sedes'
      path: '/sedes'
      fullPath: '/sedes'
      preLoaderRoute: typeof SedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido-confirmado': {
      id: '/pedido-confirmado'
      path: '/pedido-confirmado'
      fullPath: '/pedido-confirmado'
      preLoaderRoute: typeof PedidoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderador': {
      id: '/moderador'
      path: '/moderador'
      fullPath: '/moderador'
      preLoaderRoute: typeof ModeradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cajero': {
      id: '/cajero'
      path: '/cajero'
      fullPath: '/cajero'
      preLoaderRoute: typeof CajeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderador/': {
      id: '/moderador/'
      path: '/'
      fullPath: '/moderador/'
      preLoaderRoute: typeof ModeradorIndexRouteImport
      parentRoute: typeof ModeradorRoute
    }
    '/cajero/': {
      id: '/cajero/'
      path: '/'
      fullPath: '/cajero/'
      preLoaderRoute: typeof CajeroIndexRouteImport
      parentRoute: typeof CajeroRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderador/historial': {
      id: '/moderador/historial'
      path: '/historial'
      fullPath: '/moderador/historial'
      preLoaderRoute: typeof ModeradorHistorialRouteImport
      parentRoute: typeof ModeradorRoute
    }
    '/cajero/historial': {
      id: '/cajero/historial'
      path: '/historial'
      fullPath: '/cajero/historial'
      preLoaderRoute: typeof CajeroHistorialRouteImport
      parentRoute: typeof CajeroRoute
    }
    '/api/staff-users': {
      id: '/api/staff-users'
      path: '/api/staff-users'
      fullPath: '/api/staff-users'
      preLoaderRoute: typeof ApiStaffUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sedes': {
      id: '/admin/sedes'
      path: '/sedes'
      fullPath: '/admin/sedes'
      preLoaderRoute: typeof AdminSedesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operacion': {
      id: '/admin/operacion'
      path: '/operacion'
      fullPath: '/admin/operacion'
      preLoaderRoute: typeof AdminOperacionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marcas': {
      id: '/admin/marcas'
      path: '/marcas'
      fullPath: '/admin/marcas'
      preLoaderRoute: typeof AdminMarcasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminMarcasRoute: typeof AdminMarcasRoute
  AdminOperacionRoute: typeof AdminOperacionRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminReportesRoute: typeof AdminReportesRoute
  AdminSedesRoute: typeof AdminSedesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminMarcasRoute: AdminMarcasRoute,
  AdminOperacionRoute: AdminOperacionRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminReportesRoute: AdminReportesRoute,
  AdminSedesRoute: AdminSedesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CajeroRouteChildren {
  CajeroHistorialRoute: typeof CajeroHistorialRoute
  CajeroIndexRoute: typeof CajeroIndexRoute
}

const CajeroRouteChildren: CajeroRouteChildren = {
  CajeroHistorialRoute: CajeroHistorialRoute,
  CajeroIndexRoute: CajeroIndexRoute,
}

const CajeroRouteWithChildren =
  CajeroRoute._addFileChildren(CajeroRouteChildren)

interface ModeradorRouteChildren {
  ModeradorHistorialRoute: typeof ModeradorHistorialRoute
  ModeradorIndexRoute: typeof ModeradorIndexRoute
}

const ModeradorRouteChildren: ModeradorRouteChildren = {
  ModeradorHistorialRoute: ModeradorHistorialRoute,
  ModeradorIndexRoute: ModeradorIndexRoute,
}

const ModeradorRouteWithChildren = ModeradorRoute._addFileChildren(
  ModeradorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CajeroRoute: CajeroRouteWithChildren,
  CarritoRoute: CarritoRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  ContactoRoute: ContactoRoute,
  LoginRoute: LoginRoute,
  ModeradorRoute: ModeradorRouteWithChildren,
  NosotrosRoute: NosotrosRoute,
  PedidoConfirmadoRoute: PedidoConfirmadoRoute,
  ProductosRoute: ProductosRoute,
  SedesRoute: SedesRoute,
  UneteRoute: UneteRoute,
  ApiStaffUsersRoute: ApiStaffUsersRoute,
  ProductoSlugRoute: ProductoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
